apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "pets-backend"
  annotations:
    github.com/project-slug: mlewis-portal-demo/pets-backend
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/team-a"
